name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: Infisical/secrets-action@v1.0.7
        with:
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }} # Update this to your own Github references
          client-secret: ${{ secrets.INFISICAL_SECRET }} # Update this to your own Github references
          env-slug: "prod"
          project-slug: "learning-repo-tx-xr"
          domain: "https://eu.infisical.com"

      - name: Install Infisical CLI
        run: npm install -g infisical

      - name: Decode and Save Google Service Account JSON
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON_2" > keys.json

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed    

      - name: Compile Code
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          make deps
          make test

      - name: Build Docker Image
        run: docker build -t my-app:${{ github.sha }} -f apartment_hunt/Dockerfile .

      - name: Run Unit Tests Inside Container
        run: docker run --rm my-app:${{ github.sha }} mvn test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag my-app:${{ github.sha }} my-dockerhub-username/my-app:latest
          docker push my-dockerhub-username/my-app:latest
