name: run real_state

on:
  schedule:
    - cron: '0 5-19/6 * * *' # At minute 0 past every 2nd hour
  workflow_dispatch:

# Add the required permissions for OIDC authentication
permissions:
  id-token: write   # Required to request the JWT from GitHub
  contents: read    # Needed to access the repository contents

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: Infisical/secrets-action@v1.0.7
       with:
            method: "oidc"
            env-slug: "dev"
            project-slug: "learning-repo-tx-xr"
            identity-id: "6c8f5f43-4b3b-4bb7-be7f-352f7785848c"

     - name: checkout repo content
       uses: actions/checkout@v2 # checkout the repository content to github runner

     - name: Install Infisical CLI
       run: npm install -g infisical

     - name: Debug Environment Variables
       run: |
           echo "ID_TOKEN_REQUEST_URL: $ACTIONS_ID_TOKEN_REQUEST_URL"
           echo "ID_TOKEN_REQUEST_TOKEN: ${#ACTIONS_ID_TOKEN_REQUEST_TOKEN}"

     - name: Request OIDC Token
       run: |
             echo "Requesting OIDC token..."
             TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
             echo "TOKEN=$TOKEN" >> $GITHUB_ENV

     - name: Retrieve Secrets from Infisical
       run: |
          infisical pull -e prod --no-interactive

     - name: Decode and Save Google Service Account JSON
       run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON" | base64 --decode > keys.json

     - name: setup python
       uses: actions/setup-python@v4
       with:
          python-version: '3.9' # install the python version needed
          
     - name: install python packages
       run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
     - name: execute deuwo # run python scrip        
       run: python deuwo.py
        
     - name: execute howoge # run python scrip        
       run: python howoge.py
        
